### ISSUE TITLE
Harvesting vignette

### ISSUE THREAD

**Issue by kunstler** [gowachin/matreex#20]
Some comments

1. in 
```
**def_harv
#> function (x, species, ...) 
#> {
#>     dots <- list(...)
#>     ct <- dots$ct
#>     rate <- 0.006 * (ct > 0)
#>     return(x * rate)
#> }
#> <bytecode: 0x117180ce0>
#> <environment: namespace:matreex>
Picea_sp <- species(IPM = Picea_ipm, init_pop = def_initBA(30))
Picea_for <- forest(species = list(Picea = Picea_sp), 
                    harv_rules = c(Pmax = 0.25, dBAmin = 3, 
                                   freq = 1, alpha = 1))
```

Why do we need to provide Pmax = 0.25, dBAmin = 3, 
                                   freq = 1, alpha = 1 as this is not use ?

2. Same question in the modulation section
```
Picea_sim_f20 <- sim_deter_forest(
    forest(species = list(Picea = Picea_sp), 
                      harv_rules = c(Pmax = 0.25, dBAmin = 3, 
                                     freq = 20, alpha = 1)),
    tlim = 50,
    equil_time = 50, equil_dist = 10, equil_diff = 1,
    harvest = "default", 
    SurfEch = 0.03,
    verbose = TRUE
)
```
why provide teh parameters for Pmax dBAmin alpha ?

3. in "The maximum harvesting for large tree  can be tuned so that the probability for a large tree to be harvested approaches 1 after several harvesting operations:  hmax = 1 - \sqrt[n]{1-p} with n the number of harvesting operations." what is "p" the variable approaching 1? Maybe be add "The maximum harvesting for large tree  can be tuned so that the probability for a large tree to be harvested approaches 1 (for instance p = 0.999) after several harvesting operations:  hmax = 1 - \sqrt[n]{1-p} with n the number of harvesting operations. "
4. Je comprends pas '$P_{cut, i} = \frac{BA_{stand, i} - BA_{harv, i}}{BA_{stand, i}} = f(p_i) * P_{cut}' pourquoi c est BA_harv est pas BA_target  omme dans le cas monospecificque?

**Comment by gowachin** [comment]
1. 2. All the parameters were set in default and checked in a validation function. However they are not always used and `alpha` was not even documented for the `forest()` function. I edited this function so that the default values are merged with the user input and still pass the validation function.

3. 4. Was edited in eed3214
