### ISSUE TITLE
Disturbance vignette

### ISSUE THREAD

**Issue by kunstler** [gowachin/matreex#21]
The equation to present julien model are unclear

$$
X_{t+1} = X_t \times (1 - logist(a_0 + a_1 \times logratio.scaled + b \times I^{c \times dbh.scaled}))^t 
$$

I propose to use instead

$$
Pdeath_{i,t} = 1- (1 - logist(a_0 + a_1 \times logratio.scaled + b \times I* dbh.scaled^{c}))^t 
$$

Julien c est bien cela ? dbh.sclaed c est le dbh centré réduit ?

**Comment by kunstler** [comment]
Dans ce plot

#' Disturbance function
matreex::disturb_fun
#> function (x, species, disturb = NULL, ...) 
#> {
#>     dots <- list(...)
#>     qmd <- dots$qmd
#>     size <- species$IPM$mesh
#>     coef <- species$disturb_coef
#>     disturbance <- NULL
#>     if (any(disturb$type %in% coef$disturbance)) {
#>         coef <- subset(coef, disturbance == disturb$type)
#>     }
#>     else {
#>         stop(sprintf("The species %s miss this disturbance type (%s) parameters", 
#>             sp_name(species), disturb$type))
#>     }
#>     size[size == 0] <- min(size[size != 0])
#>     logratio <- log(size/qmd)
#>     dbh.scaled = coef$dbh.intercept + size * coef$dbh.slope
#>     logratio.scaled = coef$logratio.intercept + logratio * coef$logratio.slope
#>     Pkill <- plogis(coef$a0 + coef$a1 * logratio.scaled + coef$b * 
#>         disturb$intensity^(coef$c * dbh.scaled))
#>     return(x * Pkill)
#> }
#> <bytecode: 0x12d3b7cb8>
#> <environment: namespace:matreex>
Picea_sp$disturb_fun <- disturb_fun

C'est peut être plus simple de ne pas montrer le plateau pour les arbres < 10cm? c est bien cela la partie plate au début de la distribution?

**Comment by kunstler** [comment]
Ok avec cela 

"When simulating the effect of biotic disturbances on forests mixing coniferous and broadleaf species, an additional effect can be taken into account based on the survival models developped by @Brandl2020. This mixture effect is a linear function, and the mean of the function has been scaled to match the average mortality disturbance estimated by @Barrere2023 for the average share of conifers in the fitting data." ?

**Comment by jbarrere3** [comment]
Ok avec la proposition de Georges sur l'équation de mortalité, c'est effectivement un peu plus clair de représenter directement une probabilité de mortalité que l'effet sur les classes de taille via la mortalité. Ok aussi pour la proposition sur les perturbations biotiques. On a aussi discuté du fait que lorsqu'on montrer les équations linéaires pour "scaler" le dbh et le logratio, cette transformation permet de centrer-réduire ces deux variables avec comme moyenne et écart-type référence ceux du jeu de données utilisé pour fitter le modèle. Je fais une proposition directement dans la vignette dans ce sens si vous êtes ok.
